vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        images_food:
           uri_prefix: /media
           upload_destination: '%kernel.project_dir%/public/media'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        images_categorie:
           uri_prefix: /media
           upload_destination: '%kernel.project_dir%/public/media'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
